image:
  repository: globalshopacr.azurecr.io/globalshop-frontend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 4001
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.128.203.67.3.nip.io  # Replace with your external IP
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - frontend.128.203.67.3.nip.io  # Replace with your external IP
      secretName: frontend-tls

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
