image:
  repository: globalshopacr.azurecr.io/globalshop-frontend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 4001
  targetPort: 80

ingress:
  enabled: false

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
