name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/globalshop-backend:v1 ./app/backend
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/globalshop-frontend:v1 ./app/frontend
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/globalshop-backend:v1
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/globalshop-frontend:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set kubectl context
      run: |
        az aks get-credentials --resource-group rg-globalshop --name aks-globalshop

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3.sh | bash

    - name: Deploy to AKS using Helm
      run: |
        helm upgrade --install globalshop-frontend ./helm/globalshop-frontend
        helm upgrade --install globalshop-backend ./helm/globalshop-backend
